blueprint:
  name: Voice - Control AC Mode & Fan Speed
  author: luuquangvu
  description: |
    # Tool for Controlling Air Conditioner Mode and Fan Speed used for Voice Assistant

    ## Blueprint Setup

    ### Required

    - A smart air conditioner (climate entity) integrated into Home Assistant.
    - A template sensor stores all information about entity aliases needs to be configured in `config/configuration.yaml`; The sensor is required for friendly-name lookup.

    ```
    #File configuration.yaml
    shell_command:
      get_entity_alias: jq '[.data.entities[] | select(.options.conversation.should_expose == true and (.aliases | length > 0)) | {entity_id, aliases}]' ./.storage/core.entity_registry
    template:
      - triggers:
          - trigger: homeassistant
            event: start
          - trigger: event
            event_type: event_template_reloaded
        actions:
          - action: shell_command.get_entity_alias
            response_variable: response
        sensor:
          - name: "Assist: Entity IDs and Aliases"
            unique_id: entity_ids_and_aliases
            icon: mdi:format-list-bulleted
            device_class: timestamp
            state: "{{ now().isoformat() }}"
            attributes:
              entities: "{{ response.stdout }}"
    ```

    ### Optional

    - Adjust the prompts for each field used in the script. The descriptions guide the LLM to provide the correct input.

    ### Note

    - Provide a concise and precise description for the script. This will be utilized by the LLM to understand it should use this script for controlling modes and fan speeds of a smart air conditioner.
    - Make sure to expose the air conditioner entities you want to control to Assist.
    - Make sure to expose the script to Assist after the script has been saved.
    - Do not alter the default script name.
    - Once the script is created, click the three dots in the top right corner, choose "Edit in YAML," and remove the `description: ...` line to restore the default. This step is important because it helps the LLM better understand the script's purpose.
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    entity_aliases_settings:
      name: Settings for Entity Aliases
      icon: mdi:format-list-bulleted
      description: You can use these settings to configure a template sensor that stores all information about entity aliases.
      input:
        entity_aliases:
          name: Entity Aliases
          selector:
            entity:
              filter:
                - domain: sensor
                  integration: template
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        ac_entities_prompt:
          name: AC Entities Prompt
          description: The prompt which will be used for the LLM can provide the name of ACs for controlling.
          selector:
            text:
              multiline: true
          default: |
            This argument is mandatory and must always be included.
            Specify at least one air conditioner name to control.
            To control multiple ACs, separate each name with a semicolon.
        hvac_mode_prompt:
          name: HVAC Mode Prompt
          description: The prompt which will be used for the LLM can provide the AC mode.
          selector:
            text:
              multiline: true
          default: |
            Use this argument to set the AC mode. Accepted values: auto, cool, heat, dry, fan_only, off.
            Include this only when the user explicitly requests a mode change; otherwise omit it.
            If the requested mode is not in the device's supported modes, return an error instead of guessing or changing another field.
        fan_mode_prompt:
          name: Fan Mode Prompt
          description: The prompt which will be used for the LLM can provide the fan speed/mode of the AC.
          selector:
            text:
              multiline: true
          default: |
            Use this argument to set the AC's fan mode (fan speed). Accepted examples: auto/automatic, low/1, lowmid/2, mid/medium/3, highmid/4, high/5.
            Map qualitative or numeric requests to the closest matching supported mode; resolve per device when multiple ACs are targeted.
            Include this only when the user requests a fan speed change; otherwise omit it.
            If no supported fan mode matches for a device, return an error instead of guessing or changing another field.
mode: parallel
max_exceeded: silent
description: Controls the mode and/or fan speed of one or more specified air conditioners.
variables:
  version: 20251212
fields:
  ac_entities:
    name: AC Entities
    description: !input ac_entities_prompt
    selector:
      text:
    required: true
  hvac_mode:
    name: HVAC Mode
    description: !input hvac_mode_prompt
    selector:
      text:
  fan_mode:
    name: Fan Mode
    description: !input fan_mode_prompt
    selector:
      text:
sequence:
  - variables:
      entity_aliases: !input entity_aliases
      ac_entities: "{{ ac_entities | default('') | trim }}"
      hvac_mode: "{{ hvac_mode | default('') | trim | lower }}"
      fan_mode: "{{ fan_mode | default('') | trim | lower }}"
      alias_map:
        auto: ["auto", "automatic"]
        automatic: ["automatic", "auto"]
        low: ["low", "1", "speed1", "minimum", "lowest"]
        lowmid: ["lowmid", "2", "speed2", "lowmedium", "mediumlow"]
        mid: ["mid", "medium", "3", "speed3"]
        highmid: ["highmid", "4", "speed4", "mediumhigh"]
        high: ["high", "5", "speed5", "max", "maximum", "highest"]
  - alias: Resolve Entities and Check Existence
    variables:
      resolution: |
        {% set res = namespace(entities=[], missing_names=[]) %}
        {% for entity in ac_entities.split(';') %}
          {% set name = entity.strip() %}
          {% if name %}
            {% set exact_match = states.climate | selectattr('attributes.friendly_name', '==', name) | map(attribute='entity_id') | list %}
            {% if exact_match %}
              {% set res.entities = res.entities + exact_match %}
            {% else %}
              {% set alias_match = state_attr(entity_aliases, 'entities') | default([]) | selectattr('entity_id', 'match', 'climate\.') | selectattr('aliases', 'contains', name) | map(attribute='entity_id') | list %}
              {% if alias_match %}
                {% set res.entities = res.entities + alias_match %}
              {% else %}
                {% set res.missing_names = res.missing_names + [name] %}
              {% endif %}
            {% endif %}
          {% endif %}
        {% endfor %}
        {{ { 'entities': res.entities | unique | list, 'missing': res.missing_names } }}
  - alias: Validate Modes and Prepare Execution Data
    variables:
      processed_data: |
        {% set result = namespace(invalid=false, reasons=[], hvac_missing=[], fan_missing=[], resolved_fans=[]) %}
        {% if resolution.missing | length > 0 %}
          {% set result.invalid = true %}
          {% set result.reasons = result.reasons + ['AC not found: ' ~ (resolution.missing | join(', '))] %}
        {% endif %}
        {% if (not hvac_mode) and (not fan_mode) %}
          {% set result.invalid = true %}
          {% set result.reasons = result.reasons + ['Missing both hvac_mode and fan_mode'] %}
        {% endif %}
        {% set input_fan_norm = fan_mode | replace(' ', '') | replace('_', '') %}

        {% for entity_id in resolution.entities %}
          {% set device_name = state_attr(entity_id, 'friendly_name') %}
          
          {% if hvac_mode %}
            {% set supported_hvac = state_attr(entity_id, 'hvac_modes') | default([]) %}
            {% set hvac_support = namespace(modes=[]) %}
            {% for m in supported_hvac %}
              {% set val = m %}
              {% if m.value is defined %}{% set val = m.value %}{% else %}
                {% set s = m | string %}
                {% if 'HVACMode.' in s and ':' in s %}{% set val = s.split(':')[1].strip(" '>") %}
                {% elif 'hvacmode.' in s|lower %}{% set val = s.lower().split('hvacmode.', 1)[1] %}
                {% endif %}
              {% endif %}
              {% set hvac_support.modes = hvac_support.modes + [val | string | lower] %}
            {% endfor %}
            {% if hvac_mode not in hvac_support.modes %}
              {% set result.invalid = true %}
              {% set result.hvac_missing = result.hvac_missing + [device_name ~ ' supports: ' ~ (hvac_support.modes | join(', '))] %}
              {% set result.reasons = result.reasons + ['hvac_mode ' ~ hvac_mode ~ ' not in ' ~ (hvac_support.modes | join(', '))] %}
            {% endif %}
          {% endif %}

          {% if fan_mode %}
            {% set supported_fan = state_attr(entity_id, 'fan_modes') | default([]) %}
            {% set fan_check = namespace(matched=false, resolved_mode='') %}
            {% set fan_support = namespace(aliases=[]) %}
            
            {% for mode in supported_fan %}
              {% set norm_mode = mode | lower | replace(' ', '') | replace('_', '') %}
              {% set mode_aliases = [norm_mode] %}
              {% for canon, aliases in alias_map.items() %}
                {% if norm_mode == canon or norm_mode in aliases %}
                  {% set mode_aliases = mode_aliases + aliases %}
                {% endif %}
              {% endfor %}

              {% if input_fan_norm in mode_aliases %}
                {% set fan_check.matched = true %}
                {% set fan_check.resolved_mode = mode %}
              {% endif %}
              {% set fan_support.aliases = fan_support.aliases + mode_aliases %}
            {% endfor %}

            {% if not fan_check.matched %}
              {% set result.invalid = true %}
              {% set result.fan_missing = result.fan_missing + [device_name ~ ' supports: ' ~ (supported_fan | map('string') | list | join(', '))] %}
              {% set result.reasons = result.reasons + ['fan_mode ' ~ fan_mode ~ ' not in supported list'] %}
            {% else %}
              {% set result.resolved_fans = result.resolved_fans + [fan_check.resolved_mode] %}
            {% endif %}
          {% else %}
            {% set result.resolved_fans = result.resolved_fans + [''] %}
          {% endif %}
        {% endfor %}

        {% if result.invalid %}
          {% set result.reasons = result.reasons + ['invalid=true'] %}
        {% endif %}
        {{ {
          'invalid': result.invalid,
          'reasons': result.reasons,
          'hvac_missing': result.hvac_missing,
          'fan_missing': result.fan_missing,
          'resolved_fans': result.resolved_fans
        } }}

  - alias: Error Handling
    if:
      - condition: template
        value_template: "{{ processed_data.invalid }}"
    then:
      - variables:
          response:
            error: |
              Unable to control the air conditioner.
              {{ 'HVAC mismatch: ' ~ processed_data.hvac_missing | join(' | ') if processed_data.hvac_missing else '' }}
              {{ 'Fan mismatch: ' ~ processed_data.fan_missing | join(' | ') if processed_data.fan_missing else '' }}
              {{ 'Reasons: ' ~ processed_data.reasons | join(' | ') if processed_data.reasons else '' }}
      - stop: "Validation failed"
        response_variable: response

  - alias: Execution
    repeat:
      count: "{{ resolution.entities | length }}"
      sequence:
        - variables:
            entity_id: "{{ resolution.entities[repeat.index - 1] }}"
            target_fan: "{{ processed_data.resolved_fans[repeat.index - 1] }}"
        - choose:
            - conditions: "{{ hvac_mode != '' }}"
              sequence:
                - action: climate.set_hvac_mode
                  target:
                    entity_id: "{{ entity_id }}"
                  data:
                    hvac_mode: "{{ hvac_mode }}"
        - choose:
            - conditions: "{{ fan_mode != '' }}"
              sequence:
                - action: climate.set_fan_mode
                  target:
                    entity_id: "{{ entity_id }}"
                  data:
                    fan_mode: "{{ target_fan }}"

  - alias: Success Response
    variables:
      response:
        success: |
          {% set count = resolution.entities | length %}
          {% set names = ac_entities %}
          {% if hvac_mode and fan_mode %}
            Set {{ names }} to {{ hvac_mode }} mode with fan mode {{ fan_mode }}.
          {% elif hvac_mode %}
            Set {{ names }} to {{ hvac_mode }} mode.
          {% elif fan_mode %}
            Set fan mode {{ fan_mode }} for {{ names }}.
          {% else %}
            Updated AC settings for {{ names }}.
          {% endif %}
  - stop: Finish
    response_variable: response
