blueprint:
  name: Device Timer
  author: luuquangvu
  description: >-
    # Tool for controlling on/off devices with adjustable delay timing

    ## Blueprint Setup

    ### Note

    * The devices must support `homeassistant.turn_on` and `homeassistant.turn_off`; otherwise, errors will be logged, and the blueprint will not work.

    * This blueprint is a dependency for the `device_control_timer_full_llm.yaml` blueprint.

    * The mentioned dependency file(s) is/are included in the repository.

    * Do not alter the default script name.
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    custom_settings:
      name: Custom Settings
      icon: mdi:tools
      description: You can use these settings to configure the maximum number of simultaneous timers to run at a time.
      collapsed: true
      input:
        simultaneous:
          name: Simultaneous Timers
          selector:
            number:
              min: 10
              max: 50
          default: 30
mode: parallel
max: !input simultaneous
max_exceeded: silent
variables:
  version: 20250923
fields:
  devices:
    name: Devices
    description: Provide the names of the devices to control, separated by commas.
    selector:
        text:
    required: true
  control:
    name: Control
    description: "Action to control: use 'true' to turn on the device, or 'false' to turn off the device."
    selector:
      boolean:
    required: true
  timer:
    name: Timer
    description: The time delay to wait before executing an action.
    selector:
      time:
    required: true
sequence:
  - variables:
      devices: "{{ devices | default('') | trim }}"
      control: "{{ control | default(false) }}"
      timer: "{{ timer | default('00:00:00') }}"
  - delay: "{{ timer }}"
  - action: homeassistant.turn_{{ 'on' if control else 'off' }}
    target:
      entity_id: "{{ devices }}"
