blueprint:
  name: Voice - Get YouTube Video Details - Full LLM Script
  author: VuLQ
  description: >
    # Tool gets YouTube video info details from entity attributes

    ## Blueprint Setup

    ### Required

    * Feedparser Integration.

    * Expose YouTube Channel entities to Assist.

    ### Optional

    * Adjust the prompts for each field used in the script. The descriptions guide
    the LLM to provide the correct input.

    ### Note

    * Give the script a clear description. This will be used by the LLM to understand
    it should use this script to get the latest video info on a YouTube channel.

    * Make sure to expose the script to Assist after the script has been saved.

  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description:
        You can use these settings to finetune the prompts for your specific
        LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        entity_name_prompt:
          name: Entity Name Prompt
          description:
            The prompt which will be used to the LLM can provide the entity for the query.
          selector:
            text:
              multiline: true
              multiple: false
          default: >
            This argument is mandatory and must always be provided no matter what!

            Provide the name of which YouTube Channel entity to query video info details.

            After getting the result, ask to play the video on the TV.
mode: parallel
max_exceeded: silent
fields:
  entity_name:
    name: Entity Name
    description: !input entity_name_prompt
    selector:
        text:
    required: true
sequence:
  - variables:
      entity_name: "{{ entity_name | default }}"
  - alias: Check if variables were set correctly
    if:
      - condition: template
        value_template: "{{ not (integration_entities('feedparser') | select('is_state_attr', 'friendly_name', entity_name) | list) }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error:
              Unable to provide video info details because parameter was set incorrectly.
      - alias: Stop the script
        stop: Unable to determine the entity.
        response_variable: response
  - variables:
      entity_id: "{{ integration_entities('feedparser') | select('is_state_attr', 'friendly_name', entity_name) | first }}"
      entities: "{{ state_attr(entity_id, 'entries') }}"
      response:
        entries: >
          {% for entity in entities %}
          - title: {{ entity.title | title }}

            published: {{ strptime(entity.published, '%c').isoformat() }}

            published_relative_time: {{ strptime(entity.published, '%c') | relative_time }} ago

            media_id: {{ entity.link }}


          {% endfor %}
  - stop: ""
    response_variable: response
