---
blueprint:
  name: Link On/Off State of Multiple Devices
  author: luuquangvu
  description: |-
    # Link On/Off State of Multiple Devices
    - Select multiple entities to link their on/off state. If any selected entity is turned on or off, the other selected entities will be sent a matching on or off command.
    - Uses state filtering to prevent infinite loops and reduce network traffic. It only sends commands to devices that are not already in the desired state.
    - Automatically ignores unavailable or unknown entities to prevent errors.

    ## Requirements
    - All selected entities must support `homeassistant.turn_on` and `homeassistant.turn_off`.
    - Requires Home Assistant 2024.10.0 or newer.
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  input:
    linked_entities:
      name: Entities
      description: Entities to link together
      selector:
        entity:
          multiple: true
mode: parallel
max_exceeded: silent
variables:
  version: 20251222
  linked_entities: !input linked_entities
triggers:
  - trigger: state
    entity_id: !input linked_entities
    from: [on, off]
    to: [off, on]
actions:
  - variables:
      command: turn_{{ trigger.to_state.state }}
      target_entities: >-
        {{ expand(linked_entities)
           | selectattr('entity_id', '!=', trigger.entity_id)
           | selectattr('state', '!=', trigger.to_state.state)
           | rejectattr('state', 'in', ['unavailable', 'unknown'])
           | map(attribute='entity_id')
           | list }}
  - choose:
      - conditions: "{{ target_entities | count > 0 }}"
        sequence:
          - action: homeassistant.{{ command }}
            target:
              entity_id: "{{ target_entities }}"
