blueprint:
  name: Voice - Send to Zalo
  author: VuLQ
  description: >-
    # Tool for sending content to Zalo using LLM

    ## Blueprint Setup

    ### Required

    * Create a Zalo bot if it does not already exist using Zalo Bot Creator.

    * The Pyscript integration needs to be installed from HACS.

    * The `zalo_bot_handle_tool.py` and `common_utilities.py` scripts needs to be copied into the pyscript folder.

    * The `requirements.txt` file needs to be copied into the pyscript folder.

    * A Zalo bot token needs to be configured in `configuration.yaml`.

    * Redis needs to be installed and configured.

    ```

    #File configuration.yaml

    pyscript:
      allow_all_imports: true
      hass_is_global: true
      zalo_bot_token: !secret zalo_bot_token
      redis_host: localhost     # If you're using the Home Assistant Addon, it should be the addon's hostname: xxxxxxxx-redis
      redis_port: 6379      # Default: 6379

    ```

    ```

    #File secrets.yaml

    zalo_bot_token: XXXXXX      # Retrieve the token from the Zalo Bot Creator.

    ```

    ### Optional

    * Adjust the prompts for each field used in the script. The descriptions guide the LLM to provide the correct input.

    ### Note

    * Provide a concise and precise description for the script. This will be utilized by the LLM to understand it should use this script for sending user requested content to Zalo.

    * Make sure to expose the script to Assist after the script has been saved.

    * Do not alter the default script name.
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    zalo_settings:
      name: Settings for Zalo
      icon: mdi:application-cog
      description: You can use these settings to configure Zalo for sending the message.
      input:
        chat_id:
          name: Chat ID
          description: The chat ID to send the message to.
          selector:
            text:
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        summary_prompt:
          name: Summary Prompt
          description: The prompt which will be used for the LLM can provide the message summary.
          selector:
            text:
              multiline: true
              multiple: false
          default: >-
            This argument is mandatory and must always be provided.

            Include a brief overview, such as the name of a person, object, or location title.

            When submitting multiple items or locations, make sure each one must be sent separately through a separate tool call.
        detail_prompt:
          name: Detail Prompt
          description: The prompt which will be used for the LLM can provide the message detail.
          selector:
            text:
              multiline: true
              multiple: false
          default: >-
            This argument is optional.

            Provide clear and specific details about the content, such as comprehensive information or a detailed description of the subject.

            When submitting multiple items or locations, make sure each one must be sent separately through a separate tool call.
        location_prompt:
          name: Location Prompt
          description: The prompt which will be used for the LLM can provide the location for the place.
          selector:
            text:
              multiline: true
              multiple: false
          default: >-
            This argument is mandatory and must always be provided.

            Specify the location using only the ward and province names.

            If the content does not have a location, set the default to Google.
mode: queued
max: 20
max_exceeded: silent
fields:
  summary:
    name: Summary
    description: !input summary_prompt
    selector:
      text:
    required: true
  detail:
    name: Detail
    description: !input detail_prompt
    selector:
      text:
  location:
    name: Location
    description: !input location_prompt
    selector:
      text:
    required: true
sequence:
  - variables:
      version: 20250826
      summary: "{{ summary | default }}"
      detail: "{{ detail | default }}"
      location: "{{ location | default }}"
  - alias: Check if variables were set correctly
    if:
      - condition: template
        value_template: "{{ not (summary and location) }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: Unable to send the message to Zalo because either the summary or the location is empty.
      - alias: Stop the script
        stop: Unable to send the message to Zalo because either the summary or the location is empty.
        response_variable: response
  - variables:
      message: >-
        {{ summary }}


        {{ detail }}


        {% if location == 'Google' -%}
        {% set query = summary.split() | join('+') -%}
        {% set url = 'https://www.google.com/search?q=' + query -%}
        Google Search ({{ url }})
        {% else -%}
        {% set place = (summary ~ ' ' ~ location).split() | join('+') -%}
        {% set url = 'https://www.google.com/maps/search/' + place + '/' -%}
        Google Maps ({{ url }})
        {% endif -%}
  - action: pyscript.zalo_message_handle_tool
    data:
      chat_id: !input chat_id
      message: "{{ message }}"
    response_variable: response
