blueprint:
  name: Traffic Fine Notification
  description: >-
    # Nhận thông báo khi có thông tin phạt nguội

    * Dữ liệu được tra cứu từ Cổng thông tin điện tử Cục Cảnh sát giao thông (https://www.csgt.vn/).

  domain: automation
  homeassistant:
    min_version: 2024.10.0
  input:
    vehicles:
      name: Vehicles
      description: List of vehicles to monitor.
      selector:
        entity:
          filter:
            - domain: sensor
              integration: template
          multiple: true
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          filter:
          - integration: mobile_app
          multiple: true

mode: queued
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input vehicles

conditions:
  - condition: template
    value_template: "{{ trigger.from_state.state not in ['unavailable', 'unknown'] }}"
  - condition: template
    value_template: "{{ trigger.to_state.state not in ['unavailable', 'unknown'] }}"

actions:
  - alias: Send a notification to each device
    repeat:
      for_each: !input notify_device
      sequence:
        - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: Xe {{ trigger.to_state.attributes.friendly_name }}
            message: "{{ trigger.to_state.state }}"
            data:
              tag: "{{ 'tag_' ~ this.attributes.id }}"
